version: '3'
services:
  redisnotif:
    image: redis:latest
    container_name: gitlab-notification-redis
    ports:
     - "6479:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  nginx:
    hostname: telegram-gitlab-nginx
    image: nginx:latest
    container_name: gitlab-notification-nginx
    ports:
      - ${APP_HTTP_PORT:-3000}:80
    volumes:
      - ./:/var/www
      - ./tmp/nginx/logs:/var/log/nginx
      - ./_docker/local/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    links:
      - app
    working_dir: /var/www
  app:
    hostname: telegram-gitlab-app
    build:
      context: .
      dockerfile: _docker/local/app/Dockerfile
    container_name: gitlab-notification-app
    volumes:
      - ./:/var/www
    working_dir: /var/www
