version: '3'
services:
  redisnotif:
    image: redis:latest
    container_name: gitlab-notification-redis
    ports:
     - "6479:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  nginx:
    hostname: max-gitlab-nginx
    image: nginx:latest
    container_name: gitlab-notification-nginx
    ports:
      - ${APP_HTTP_PORT:-3000}:80
    volumes:
      - ./:/var/www
      - ./tmp/nginx/logs:/var/log/nginx
      - ./_docker/local/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    links:
      - app
    working_dir: /var/www
  app:
    hostname: max-gitlab-app
    build:
      context: .
      dockerfile: _docker/local/app/Dockerfile
    container_name: gitlab-notification-app
    volumes:
      - ./:/var/www
    depends_on:
        - db
    links:
        - db
    working_dir: /var/www
  queue:
   build:
        context: .
        dockerfile: _docker/local/app/Dockerfile
   container_name: max-notification-queue
   hostname: max-gitlab-queue
   command: php artisan queue:listen database --queue=${QUEUE_NAME:-default} --timeout=1800 --tries=${QUEUE_TRIES:-10} --delay=${QUEUE_DELAY:-3}
   restart: always
   volumes:
    - ./:/var/www
   depends_on:
    - app
  db:
    build:
      context: .
      dockerfile: _docker/local/db/Dockerfile
    container_name: gitlab-notification-db
    volumes:
      - ./tmp/postgresql_max_gitlab_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 15513:5432
